version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example


  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER: mysql    
    ports:
      - 8081:8080
      
      
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 5673:5672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user123      
      
